#!/bin/bash

# Training Parameters
h1_size=320
h2_size=320
h3_size=160
fr_size=4
eps_step=10800
lr=1e-5

# Eps counter parameters
eps_start=1.0
eps_end=0.1
eps_dec=-0.1

for eps in $(seq $eps_start $eps_dec $eps_end)
    do
        python3 dqn_bullet.py --INIT_EPS $eps

done

#python3 dqn_bullet.py --H1_SIZE $h1_size --H2_SIZE $h2_size --H3_SIZE $h3_size --MAX_EXPERIENCE 20000 --FRAME_COUNT $fr_size --EPS_ANNEAL_STEPS $eps_step --INIT_EPS 0.8
#python3 dqn_bullet.py --H1_SIZE $h1_size --H2_SIZE $h2_size --H3_SIZE $h3_size --MAX_EXPERIENCE 20000 --FRAME_COUNT $fr_size --EPS_ANNEAL_STEPS $eps_step --INIT_EPS 0.6
#python3 dqn_bullet.py --H1_SIZE $h1_size --H2_SIZE $h2_size --H3_SIZE $h3_size --MAX_EXPERIENCE 20000 --FRAME_COUNT $fr_size --EPS_ANNEAL_STEPS $eps_step --INIT_EPS 0.4

# Shut down if before 9 am
currenttime=`date +"%H:%M"`
if [[ "$currenttime" > "23:00" ]] || [[ "$currenttime" < "08:30" ]]; then
#    echo Hi
    echo "$currenttime"
#    sudo poweroff
else
    echo Bye
fi
